/** Official schedule checked September 19, 2026: https://my.hackthenorth.com/schedule */
const schedule = "https://my.hackthenorth.com/schedule";
const end = "2026-09-20T16:30:00-04:00";
const closing = "2026-09-20T14:30:00-04:00";
const start = "2026-09-18T00:00:00-04:00";
const evidencePolicy = " All times are EDT (America/Toronto). Resolve NO only when the stated source provides enough evidence to rule out YES; otherwise VOID. If the relevant event is cancelled or no usable record is available within 48 hours of the expected result time, VOID. Expected result times are review targets, not automatic outcomes. For markets whose trading cutoff is an event start, a schedule change requires closing trading before the revised event start and publishing an update. Never reopen or extend trading after the outcome is known.";

export interface HtnMarket {
  slug: string; title: string; shortTitle: string; description: string; rules: string;
  resolutionSource: string; category: string; icon: string; color: string; featured: boolean;
  closesAt: string; resolvesAt: string; openingProbability: number; pricingRationale: string;
}

function market(slug: string, title: string, description: string, rules: string, openingProbability: number, pricingRationale: string, options: Partial<HtnMarket> = {}): HtnMarket {
  return {
    slug: `htn-2026-${slug}`, title, shortTitle: title, description,
    rules: rules + evidencePolicy + ` Opening YES estimate: ${Math.round(openingProbability * 100)}%, set by Goosey. ${pricingRationale}`,
    resolutionSource: `Official HTN schedule (${schedule}); official closing-ceremony recording and published project gallery or winner announcement, as specified in the rules.`,
    category: "Hack the North", icon: "sparkles", color: "gold", featured: false,
    closesAt: closing, resolvesAt: end, openingProbability, pricingRationale,
    ...options,
  };
}

const gooseRules = "Count distinct, unprovoked goose incidents involving HTN attendees on the University of Waterloo campus from September 18 at 12:00 a.m. through September 20 at 4:30 p.m. A qualifying incident is a goose chasing, pecking, biting, or striking a person; a hiss or nearby goose alone does not count. The reporting window runs from publication of these markets until September 20 at 4:30 p.m.; reports may describe earlier incidents in the incident window. Evidence must be posted in the comments of any market in this goose-count event by 4:30 p.m. Sunday, with an incident time, location, and either timestamped video or two independent firsthand accounts. Moderators publish one deduplicated incident list for all three thresholds. Multiple reports or people in one continuous encounter count once. Exclude deliberate provocation, feeding, handling, staged incidents, and invented reports. Do not approach or provoke wildlife. If comments were available throughout the reporting window and no qualifying reports arrive, the count is zero; if the reporting record is unavailable or materially incomplete, VOID.";

export const htnMarkets: HtnMarket[] = [
  ...[
    { count: 1, price: 0.60, title: "Will the geese choose violence at HTN?", copy: "One thousand hackers. Home-field advantage for the geese. Do we get even one verified goose incident?", rationale: "Editorial estimate: one incident is plausible across a large campus event; no incident-rate dataset is available." },
    { count: 3, price: 0.35, title: "Three goose attacks. Are we cooked?", copy: "At what point is this their hackathon? YES needs at least three separate, verified incidents.", rationale: "Editorial estimate: three separate verified incidents is a higher bar than one." },
    { count: 6, price: 0.15, title: "Six goose attacks: has campus been claimed?", copy: "The geese are putting up numbers. Will the verified incident count hit six?", rationale: "Editorial estimate: six verified, unprovoked incidents is a tail outcome, not a measured forecast." },
  ].map(({ count, price, title, copy, rationale }) => market(`goose-incidents-${count}`, title, copy, `Resolves YES if the shared verified incident count is at least ${count}; otherwise NO, subject to the reporting rules. ${gooseRules}`, price, rationale, { category: "Memes", icon: "bird", color: "sky", featured: count === 1, closesAt: end, resolutionSource: "Timestamped reports in this event's three market comment sections and the moderator's deduplicated incident list. Reporting cutoff: September 20, 2026, 4:30 p.m. EDT." })),
  market("waterloo-home-win", "Will Waterloo defend home turf?", "Home crowd, home Wi-Fi, home geese. Will a Waterloo-majority team take an overall winner spot?", "YES if an officially announced overall winning HTN project has more than half its listed members enrolled at the University of Waterloo on September 18, 2026. Sponsor-only prizes do not count. Use official results and team members' public enrollment confirmations; do not infer enrollment from names or appearance. HTN need not rank winners first, second, or third. If eligibility cannot be established for all overall winning teams, VOID rather than assuming NO.", 0.60, "Editorial estimate: Waterloo's host-campus presence gives it a plausible advantage; team composition is unknown.", { category: "Waterloo", icon: "trophy", featured: true }),
  market("goosey-prize", "Will Goosey actually win something?", "We've made the market. Now we have to face the judges. Does Goosey leave HTN with a prize?", "YES if the Goosey project is named as a winner of at least one official HTN 2026 overall or sponsor project prize announced by 4:30 p.m. Sunday. Participation swag, random raffles, side-event prizes, and honorable mentions without a prize do not count. Use the official winners list or sponsor announcement. If Goosey does not submit, NO; an incomplete winners list is insufficient for NO.", 0.25, "Editorial estimate: any sponsor prize counts, but judging and the eligible field are unknown.", { icon: "trophy", featured: true }),
  market("freshman-poker", "Will a first-year take everyone's chips?", "Saturday poker night. Someone just survived orientation. Are they about to win the whole table?", "YES if at least one official first-place winner of Saturday's Poker Tournament is in their first year of an undergraduate program. Use the tournament host's final results and the winner's voluntary public confirmation of year of study. Joint first-place winners count; guesses based on age or appearance do not. No final result or no confirmation of the winner's year means VOID.", 0.35, "Editorial estimate: first-years are a subset of attendees; no entrant breakdown is available.", { category: "Sports", icon: "trophy", color: "green", closesAt: "2026-09-19T20:30:00-04:00", resolvesAt: "2026-09-19T22:00:00-04:00", resolutionSource: `Official Poker Tournament host's results and winner's public confirmation; ${schedule} lists Saturday 8:30–10 p.m.` }),
  market("closing-job-shoot-your-shot", "Will someone ask for a job on the closing mic?", "The demo is done. The recruiter is right there. Does someone skip LinkedIn and shoot their shot?", "YES if a speaker, presenter, or audience member on the official closing-ceremony microphone directly asks a named company or its representative for a job, internship, interview, or referral. An explicit joke request counts; generic 'we're hiring' announcements and private conversations do not. Judge only the full official closing-ceremony recording, 2:30–4:30 p.m. Sunday. Incomplete audio means VOID unless YES is already established.", 0.30, "Editorial estimate: a public recruiting request is possible but a narrower condition than general job talk.", { category: "Memes", color: "violet" }),
  market("hardware-winner", "Will actual hardware beat the wrappers?", "Wires everywhere. One deeply stressed teammate. Will a hardware build land an overall winner spot?", "YES if at least one officially announced overall winning project needs a custom-built or custom-programmed physical device for its core demonstrated feature. Microcontrollers, robots, wearables, and custom sensor systems qualify. A normal laptop, phone, or an off-the-shelf headset by itself does not. Sponsor-only prizes do not count. Check the official winners and submitted demos; do not assume HTN awards a single first place.", 0.60, "Editorial estimate: any overall winning slot qualifies, but the finalist field is not yet known.", { category: "Projects", icon: "cpu", color: "blue" }),
  market("closing-honk", "Will someone say 'honk' on the closing mic?", "One word. A room full of Waterloo people. Surely someone does it.", "YES if a person audibly says the standalone word 'honk' into the official microphone during closing ceremonies, 2:30–4:30 p.m. Sunday. A spoken 'honk honk' counts. Bird sounds, recordings, text on a slide, and unamplified audience shouts do not. Use the full official recording; incomplete audio means VOID unless YES is established.", 0.40, "Editorial estimate: a campus-relevant joke is plausible, but the exact spoken word is a strict condition.", { category: "Memes", icon: "bird", featured: true, color: "sky" }),
  market("ramen-before-sunrise", "Will we boil noodles before we ship code?", "Forget boiling the ocean. At 3 a.m., one hot cup of ramen is an infrastructure project.", "YES if at least one attendee receives a ready-to-eat hot ramen serving from the official Overnight Ramen service between 3:00 a.m. inclusive and 3:15 a.m. exclusive on Sunday. Setup, unopened dry noodles, and attendee-made food do not count. Use timestamped service footage or confirmation from the food-service host. Trading closes at the scheduled 3:00 a.m. service start.", 0.65, "Editorial estimate: service is scheduled for 3 a.m.; fifteen minutes allows some setup delay without assuming on-time service.", { category: "Food", icon: "utensils", color: "orange", closesAt: "2026-09-20T03:00:00-04:00", resolvesAt: "2026-09-20T03:15:00-04:00", resolutionSource: `Official food-service host confirmation or timestamped service footage; ${schedule} lists Overnight Ramen Sunday 3–7 a.m.` }),
  market("karaoke-rickroll", "Will karaoke get Rickrolled?", "Two hours of karaoke. A tent full of hackers. You know the song.", "YES if someone performs at least 30 continuous seconds of Rick Astley's 'Never Gonna Give You Up' during official Saturday karaoke at the RBC Oasis Tent, 9–11 p.m. Singing along to the backing track counts; background playback with nobody performing does not. Use timestamped event footage or the karaoke host's complete performed-song list. NO requires a complete list or recording.", 0.55, "Editorial estimate: a familiar internet singalong has a reasonable chance during a two-hour hacker karaoke session.", { category: "Memes", color: "violet", featured: true, closesAt: "2026-09-19T21:00:00-04:00", resolvesAt: "2026-09-19T23:00:00-04:00", resolutionSource: `Karaoke host's complete performed-song list or event recording; ${schedule} lists Saturday 9–11 p.m., RBC Oasis Tent.` }),
  market("boba-before-345", "Will the boba arrive before we lose it?", "The afternoon slump is real. Will the first bubble tea make it into a hacker's hands before 3:45?", "YES if the official Bubble Tea Snack serves its first attendee before 3:45 p.m. Saturday, September 19. Trading closes at its scheduled 3:30 p.m. start. Sponsor display cups, staff drinks, and independently purchased bubble tea do not count. Use timestamped service footage or the official service host's first-serving confirmation.", 0.65, "Editorial estimate: fifteen minutes of slack beyond the published start favors YES, without claiming delivery data.", { category: "Food", icon: "utensils", color: "orange", closesAt: "2026-09-19T15:30:00-04:00", resolvesAt: "2026-09-19T15:45:00-04:00", resolutionSource: `Bubble Tea Snack host confirmation or timestamped service footage; ${schedule} lists Saturday 3:30–5:30 p.m.` }),
  market("goose-final-demo", "Will a goose make the final demo?", "A plushie. A rogue animation. An entire goose-powered startup. Does one get screen time?", "YES if a recognizable goose is visibly included in an official finalist's presented project or deliberate demo prop during Sunday's closing ceremonies. Drawings, generated images, video, and plushies count. Ambient venue branding, audience clothing, and an unrelated background goose do not. Use the full official finalist presentation recording.", 0.45, "Editorial estimate: goose references fit the campus, but reaching a finalist demo is a substantial filter.", { category: "Memes", icon: "bird", color: "sky" }),
  market("demo-gremlins", "Will a finalist get hit by the demo gods?", "It worked five minutes ago. Will a finalist have to restart or abandon their live demo on stage?", "YES if an official finalist explicitly restarts their app or device, or abandons an attempted live core-feature demonstration because it fails, during Sunday's closing ceremonies. A presenter must acknowledge the technical failure, or it must be directly visible in the recording. Minor loading delays, planned videos, and deliberate restarts that are part of the demo do not count. Use the full official finalist presentation recording.", 0.60, "Editorial estimate: multiple live presentations create several opportunities for a visible failure, but no historical failure rate is claimed.", { category: "Projects", icon: "presentation", color: "red" }),
];

export const htnEvents = [
  { slug: "htn-2026-goose-watch", title: "How many goose attacks will be reported at Hack the North?", shortTitle: "The goose incident counter", description: "Three YES/NO thresholds, one shared verified incident count. Reports close Sunday at 4:30 p.m. EDT. These are overlapping thresholds, not mutually exclusive outcomes.", category: "Memes", featured: true, color: "sky", icon: "bird", startsAt: start, endsAt: end, marketSlugs: htnMarkets.filter(m => m.slug.includes("goose-incidents-")).map(m => m.slug) },
  { slug: "htn-2026-after-hours", title: "Boba, bad singing, and questionable sleep", shortTitle: "Side quests", description: "The official schedule says fun. Your sleep schedule says otherwise.", category: "Hack the North", featured: true, color: "violet", icon: "sparkles", startsAt: "2026-09-19T15:30:00-04:00", endsAt: "2026-09-20T07:00:00-04:00", marketSlugs: ["freshman-poker", "ramen-before-sunrise", "karaoke-rickroll", "boba-before-345"].map(s => `htn-2026-${s}`) },
  { slug: "htn-2026-final-boss", title: "The final demo. What could go wrong?", shortTitle: "Closing time", description: "Prizes, public job applications, and the occasional honk. Sunday, 2:30–4:30 p.m. EDT.", category: "Hack the North", featured: true, color: "gold", icon: "trophy", startsAt: closing, endsAt: end, marketSlugs: htnMarkets.filter(m => m.closesAt === closing).map(m => m.slug) },
];
