import Link from "next/link";

export default function TermsPage() {
  return <div className="page-shell reading-page">
    <header className="page-header"><span className="eyebrow">Legal</span><h1>Terms of Use</h1><p>Last updated September 19, 2026</p></header>
    <section><h2>Acceptance of these terms</h2><p>By creating or using a Goosey account, you agree to these Terms of Use, the <Link href="/rules">community rules and market policies</Link>, and the practices described in the <Link href="/privacy">Privacy Notice</Link>. If you do not agree, do not create or use an account.</p></section>
    <section><h2>Account information</h2><p>You must provide accurate account information and may maintain only the accounts permitted by Goosey&apos;s community rules. You are responsible for safeguarding your password, maintaining control of your account, and promptly reporting suspected unauthorized access.</p></section>
    <section id="account-email"><h2>Account email and electronic communications</h2><p>You must register with a valid, current email address that you own or lawfully control and monitor regularly. You are responsible for maintaining access to that address and keeping it current. Goosey may require you to verify or re-verify the address before you can access certain features, establish eligibility, recover an account, or receive an award or payment.</p><p>To the extent permitted by applicable law, account, security, and legal notices sent to the email address then associated with your account will be treated as delivered when sent, unless Goosey receives notice that delivery failed. This does not override any consent, delivery, or notice requirement imposed by applicable law. If your address becomes inaccurate or inaccessible and no account control is available to update it, use the site&apos;s Report an issue link to request assistance promptly.</p></section>
    <section id="prizes"><h2>Prizes, awards, and payments</h2><p>Goosey may separately offer a cash prize or other award under additional eligibility criteria, official rules, or written program terms. If Goosey determines that you are eligible, your verified registered email address will be used to identify and contact the intended account holder and to obtain information reasonably required to administer payment.</p><p>Any payment or award remains subject to the applicable written terms and any required identity, age, residency, tax, sanctions, fraud-prevention, and payment-method checks. An email address is a contact and account identifier, not a payment method. Registering or verifying an address, holding feathers, appearing on a leaderboard, or using Goosey does not itself create or guarantee eligibility for money, property, or a prize.</p></section>
    <section><h2>Play-money feathers</h2><p>Feathers are free play-money units. They have no cash value, are not cash equivalents, and cannot be purchased from or redeemed through Goosey for money, property, or prizes. A feather balance does not create a property right or payment entitlement. Market settlement credits or debits feathers only and is separate from any independently offered prize or award.</p></section>
    <section><h2>Fair use and market integrity</h2><p>You may not use bots, unauthorized alternate accounts, manipulation, harassment, nonpublic information, or other conduct prohibited by the community rules. Goosey may restrict or suspend access when reasonably necessary to protect users, market integrity, security, or legal compliance.</p></section>
    <section><h2>Market information and availability</h2><p>Market prices are community forecasts, not facts, financial advice, or guarantees. Market outcomes are determined under each market&apos;s published rules and sources. Goosey may be unavailable, delayed, or changed, and no uninterrupted or error-free service is promised.</p></section>
    <section><h2>Independent project</h2><p>Goosey is an independent community project and is not an official University of Waterloo or Hack the North service. References to those organizations do not imply sponsorship, endorsement, or administration of Goosey or any separately offered award unless expressly stated in written program terms.</p></section>
    <section><h2>Changes and contact</h2><p>Goosey may update these terms prospectively. Material changes will be communicated through the service or the authoritative email associated with your account where required. Questions or account-email corrections may be submitted through the site&apos;s Report an issue link.</p></section>
  </div>;
}
