import Link from "next/link";

export default function PrivacyPage() {
  return <div className="page-shell reading-page">
    <header className="page-header"><span className="eyebrow">Legal</span><h1>Privacy Notice</h1><p>Last updated September 19, 2026</p></header>
    <section><h2>Information Goosey collects</h2><p>Goosey collects the account information you provide, including your email address, username, password hash, profile settings, and any information you submit through markets or community features. Goosey also processes trading activity, balances, positions, comments, notifications, linked-device information, session and security records, and technical data needed to operate and protect the service.</p></section>
    <section><h2>How your email is used</h2><p>Your email is not displayed as public profile information. Goosey uses it to create and secure your account, verify that you control the address, deliver account-recovery links, send required account, security, and legal notices, respond to support requests, prevent abuse, and contact you about any prize, award, reimbursement, or payment for which you may qualify.</p></section>
    <section><h2>Prize and payment administration</h2><p>If Goosey determines that you are eligible for a separately offered payment or award, the verified email associated with your account will identify and contact the intended account holder. Goosey may then request and process additional identity, eligibility, tax, and payment information required to administer that payment. The email address itself is not a payment method and does not establish eligibility.</p></section>
    <section><h2>When information is disclosed</h2><p>Goosey may disclose information to service providers that support hosting, email delivery, security, account support, analytics, or payment administration; to administrators and professional advisers who need it for legitimate operational or legal purposes; when required by law; or when necessary to protect users, Goosey, or the public. Public profile, trading, leaderboard, and community information remains visible as described in the service.</p></section>
    <section><h2>Retention and security</h2><p>Goosey retains information for as long as reasonably necessary to operate the service, maintain security and accounting records, resolve disputes, administer any award, and meet legal obligations. Reasonable safeguards are used, but no system or transmission method can be guaranteed completely secure.</p></section>
    <section><h2>Your responsibilities and choices</h2><p>You are responsible for providing an accurate email address that you own or lawfully control, monitoring it, and keeping it current. Profile and leaderboard choices are available in account settings. If your account email is no longer accurate or accessible, use the site&apos;s Report an issue link to request assistance.</p></section>
    <section><h2>Related terms</h2><p>This notice should be read with the <Link href="/terms">Terms of Use</Link> and <Link href="/rules">community rules and market policies</Link>.</p></section>
  </div>;
}
